# SQL Reminders 

## What you'll learn in this course 🧐🧐

If you haven't followed our courses on SQL, here are a few commands that you need to know in order to understand the following courses well. In this course you will learn:

- Databases concepts
- Basic commands

## SQL Concept 💽

A database is a collection of structured information stored in a computer's memory or hard disk. There are several types of databases. In this course, we will focus on relational databases, which are the most popular in business. Just like Excel, a relational database consists of 2-dimensional tables made up of rows and columns.

Generally, a database is accessed via a DBMS (Database Management System). This is an interface that allows you to access, add, modify and secure data on your server.

![Sample SQL Schema](https://full-stack-assets.s3.eu-west-3.amazonaws.com/images/Sample+SQL+Schema.png)

### Table 

Each table (or relation) consists of rows and columns. Each column defines the type of data you have, while the rows represent each entry (data) in your table.

### Schema

A database does not have only one table, that's why we have what is called a Schema. It is the set formed by the different tables and the relationships between each of them.

### Lines

Also called record, a line represents a specific instance of your table. For example, each of your customers would be a row in your company's Customer table.

### Columns

Also called field, the columns represents the structure of your database. Each column has a name and stores information of a specific type. For example, one column will represent the names of your customers while another will represent the revenue generated by each customer.

Here is a list of the different types of data:

- INTEGER, positive or negative integers
- TEXT, string
- DATE, date formatted as follows : YYYY - MM - DD 
- REAL/FLOAT, decimal number
- NULL, represents values that are either unknown or missing. Warning 0 is not NULL.

## Basic SQL Commands ⌨️⌨️

### CREATE TABLES 

```sql
CREATE TABLE table_name (

 column_name_1 data_type,

 column_name_2 data_type,

 column_name_3 data_type

);

```

### INSERT VALUES 

```sql 
INSERT INTO food_trucks

(id, name, rating, food_type)

VALUES

(1, 'Camion qui fume', 4.5, 'Burgers' );
```

### SELECT VALUES 

```sql 
SELECT column_name FROM table_name;
```

### FILTER VALUES 

```sql 
SELECT column_name FROM table_name
WHERE column_name > a_value
``` 

### GROUP VALUES 

```sql 
SELECT column_name FROM IMDB.movies
GROUP BY another_column_name
```

### JOINS 

```sql 
SELECT column_1_name, column_2_name

FROM schema.table_1_name 

INNER JOIN schema.table_2_name

ON table_1_name.column_primary_key = table_2_name.column_foreign_key;
```

## Resources 📚📚

* <a href="https://www.jedha.co/programme/bootcamp-fondamentaux" target="_blank">Jedha Essentials Bootcamp</a>